substitutions:
  # Unique name for the device in Home Assistant and network
  name: "al60"
  # Friendly name displayed in UIs
  friendly_name: "NIX labs AL60 Clock"
  # Firmware version
  version: "0.9.0"
  # Default Time Zone (can be changed in Web UI later)
  # Format must match standard TZ database names
  time_zone: "Australia/Brisbane"

packages:
  # Core system config (Logger, API, Web Server)
  core: github://n33174/nixr_dev/packages/al60_core.yaml@v${version}
  # Timekeeping (RTC, SNTP, Alarms)
  time: github://n33174/nixr_dev/packages/al60_time.yaml@v${version}
  # Environmental & Presence Sensors
  sensors: github://n33174/nixr_dev/packages/al60_sensors.yaml@v${version}
  # Buttons & Physical Inputs
  inputs: github://n33174/nixr_dev/packages/al60_inputs.yaml@v${version}
  # LED Display & Visual Effects
  light: github://n33174/nixr_dev/packages/al60_light.yaml@v${version}

wifi:
  # Disable power save to ensure responsive web interface and API
  power_save_mode: none
  
  # Fallback Access Point
  # If no WiFi is configured or connection fails, the clock creates this hotspot
  # Connect to this to set up your WiFi credentials
  ap:
    password: "12345678"

# Dashboard Import
# Allows this device to be easily adopted into ESPHome Dashboard
dashboard_import:
  package_import_url: github://n33174/nixr_dev/al60.yaml@v${version}
  # Set mport_full_config to true to import all packages allowing for full customisation
  import_full_config: false

external_components:
  # The custom component driving the clock faces
  - source: github://n33174/nixr_dev@v${version}
    components: [ ring_clock ]
