substitutions:
  # Unique name for the device in Home Assistant and network
  name: "al60"
  # Friendly name displayed in UIs
  friendly_name: "NIX labs AL60 Clock"
  # Firmware version
  version: "0.9.0"
  # Fallback Time Zone in case auto-detection fails
  # Should be POSIX Timezone String
  # Find yours here: https://github.com/nayarsystems/posix_tz_db/blob/master/zones.csv
  time_zone: "AEST-10" 

wifi:
  # Disable power save to ensure responsive web interface and API
  power_save_mode: none
  
  # Fallback Access Point
  # If no WiFi is configured or connection fails, the clock creates this hotspot
  # Connect to this to set up your WiFi credentials
  ap:
    password: "12345678"

packages:
  core:
    url: https://github.com/n33174/nixr_dev
    file: packages/al60_core.yaml
    ref: v${version}
  time:
    url: https://github.com/n33174/nixr_dev
    file: packages/al60_time.yaml
    ref: v${version}
  sensors:
    url: https://github.com/n33174/nixr_dev
    file: packages/al60_sensors.yaml
    ref: v${version}
  inputs:
    url: https://github.com/n33174/nixr_dev
    file: packages/al60_inputs.yaml
    ref: v${version}
  light:
    url: https://github.com/n33174/nixr_dev
    file: packages/al60_light.yaml
    ref: v${version}

external_components:
  # The custom component driving the clock faces
  - source:
      type: git
      url: https://github.com/n33174/nixr_dev
      ref: v${version}
    components: [ ring_clock ]
