substitutions:
  name: "al60"
  friendly_name: "NIX labs AL60 Clock"
  time_zone: "Australia/Brisbane"
  # Audio Settings
  timer_sounds_restore_mode: RESTORE_DEFAULT_ON
  alarm_sound_restore_mode: RESTORE_DEFAULT_ON

packages:
  core: github://n33174/nixr_dev/common/core.yaml@main
  time: github://n33174/nixr_dev/common/time.yaml@main
  sensors: github://n33174/nixr_dev/common/sensors.yaml@main
  inputs: github://n33174/nixr_dev/common/inputs.yaml@main
  light: github://n33174/nixr_dev/common/light.yaml@main

wifi:
  power_save_mode: none
  # Set up a wifi access point
  ap:
    password: "12345678"

# This should point to the public location of this yaml file.
dashboard_import:
  package_import_url: github://n33174/nixr_dev/al60.yaml@main
  import_full_config: false # or true

external_components:
  - source: github://n33174/nixr_dev@main
    components: [ ring_clock ]
