substitutions:
  name: "al60"
  friendly_name: "NIX labs AL60 Clock"
  version: "0.9.1"
  time_zone: "AEST-10" 

wifi:
  power_save_mode: none
  ap:
    password: "12345678"

packages:
  # Using local paths for the GitHub Action Build
  core: !include packages/al60_core.yaml
  time: !include packages/al60_time.yaml
  sensors: !include packages/al60_sensors.yaml
  inputs: !include packages/al60_inputs.yaml
  light: !include packages/al60_light.yaml

dashboard_import:
  package_import_url: github://n33174/nixr_dev/al60.yaml@v${version}
  import_full_config: true

external_components:
  # Using local paths for the GitHub Action Build
  - source:
      type: local
      path: components
    components: [ ring_clock ]