substitutions:
  name: "al60"
  friendly_name: "NIX labs AL60 Clock"
  time_zone: "Australia/Brisbane"
  # Audio Settings
  timer_sounds_restore_mode: RESTORE_DEFAULT_ON
  alarm_sound_restore_mode: RESTORE_DEFAULT_ON

packages:
  core: github://n33174/nixr_dev/common/core.yaml@main
  time: github://n33174/nixr_dev/common/time.yaml@main
  sensors: github://n33174/nixr_dev/common/sensors.yaml@main
  inputs: github://n33174/nixr_dev/common/inputs.yaml@main
  light: github://n33174/nixr_dev/common/light.yaml@main

wifi:
  power_save_mode: none
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  reboot_timeout: 0s

  manual_ip:
    static_ip: 192.168.20.57
    gateway: 192.168.20.1
    subnet: 255.255.255.0
    dns1: 192.168.20.1

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "AL60 Fallback Hotspot"
    password: "SPt0OFUb7nPR"

external_components:
  - source: github://n33174/nixr_dev@main
    components: [ ring_clock ]
    refresh: 1s
