substitutions:
  # Dev device name & settings
  name: "al60"
  friendly_name: "NIX labs AL60 Clock"
  version: 0.9.0
  time_zone: "Australia/Brisbane"

packages:
  # Loading common components from GitHub "main" branch for development testing
  core: github://n33174/nixr_dev/common/core.yaml@main
  time: github://n33174/nixr_dev/common/time.yaml@main
  sensors: github://n33174/nixr_dev/common/sensors.yaml@main
  inputs: github://n33174/nixr_dev/common/inputs.yaml@main
  light: github://n33174/nixr_dev/common/light.yaml@main

wifi:
  power_save_mode: none
  
  # Hardcoded credentials for development convenience
  # Use secrets definition in your secrets.yaml file
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  reboot_timeout: 0s

  # Static IP to make flashing and logging predictable during dev
  manual_ip:
    static_ip: 192.168.20.57
    gateway: 192.168.20.1
    subnet: 255.255.255.0
    dns1: 192.168.20.1

  # Fallback hotspot config
  ap:
    ssid: "AL60 Fallback Hotspot"
    password: "SPt0OFUb7nPR"

ota:
  # Over-the-air update password
  - platform: esphome
    password: "59ddefdfc18e3fa945ca6e45eb73ef47"

external_components:
  # Load the custom ring_clock component
  # Refresh set to 1s to ensure latest code changes are pulled immediately on compile
  - source: github://n33174/nixr_dev@main
    components: [ ring_clock ]
    refresh: 1s
