esphome:
  on_boot:
    # Display booting effect
    - priority: 800
      then:
        - logger.log: 
            format: "Booting 123"
            level: DEBUG
        - lambda: 'id(RingClock)->set_state(ring_clock::state::booting);'
    # Restore brightness and last used effect on boot
    - priority: 300
      then:
        - lambda: |-
            auto call = id(ring_light).turn_on();
            call.set_brightness(id(standard_percentage).state / 100.0f);
            call.set_effect(id(last_clock_effect));
            call.perform();
  on_shutdown:
    # Clean shutdown of the clock ring state
    - priority: 700
      then:
        - lambda: 'id(RingClock)->set_state(ring_clock::state::shutdown);'

globals:
  # Variable to persist the selected clock effect (Clock, Fade, Rainbow)
  - id: last_clock_effect
    type: std::string
    restore_value: yes
    initial_value: '"Clock"'

number:
  # Brightness slider for Active/Presence detected state
  - platform: template
    id: standard_percentage
    name: "Standard Brightness Percentage"
    optimistic: True
    restore_value: True
    unit_of_measurement: "%"
    initial_value: 50
    min_value: 1
    max_value: 100
    step: 1
    web_server:
      sorting_group_id: sorting_clock
      
  # Brightness slider for Inactive/No presence state
  - platform: template
    id: low_percentage
    name: "Low or Off Brightness Percentage"
    optimistic: True
    restore_value: True
    unit_of_measurement: "%"
    initial_value: 25
    min_value: 1
    max_value: 100
    step: 1
    web_server:
      sorting_group_id: sorting_clock

switch:
  # Toggles for specific visual elements
  - platform: template
    name: "Enable Seconds"
    id: enable_seconds
    optimistic: True
    restore_mode: RESTORE_DEFAULT_ON
    web_server:
      sorting_group_id: sorting_clock
  - platform: template
    name: "Enable Markers"
    id: enable_markers
    optimistic: True
    restore_mode: RESTORE_DEFAULT_ON
    web_server:
      sorting_group_id: sorting_clock

# Custom Component: Ring Clock Logic
# Links sensors, inputs, and lights together
ring_clock:
  # Core components
  id: RingClock
  time_id: rtc_time
  light_id: ring_light
  # Display settings
  enable_markers: enable_markers
  enable_seconds: enable_seconds
  # Color pointers for customisation
  hour_hand_color: hour_hand_color
  minute_hand_color: minute_hand_color
  second_hand_color: second_hand_color
  marker_color: marker_color
  notification_color: notification_color
  # Sensors
  sound_enabled_switch: timer_sounds
  temperature_sensor: temp_sensor
  humidity_sensor: humidity_sensor
  
  # Event Handlers (Logic)
  on_ready:
    then:
      - lambda: |-
          auto call = id(ring_light).turn_on();
          call.set_brightness(id(standard_percentage).state / 100.0f);
          call.set_effect(id(last_clock_effect));
          call.perform();
  on_alarm_triggered:
    then:
      - if:
          condition:
            - switch.is_on: alarm_sound
          then:
            - rtttl.play: "alarm:d=16,o=6,b=140:c,e,g,c7,g,e,c,g,e,g,b,e7,b,g,e,b,4c7,p,4c7,p,4c7,p"
  on_timer_finished:
    then:
      - rtttl.play: "timer_alert:d=16,o=6,b=120:c,e,g,c7,p,g,e,c,p,c,e,g,c7,p,g,e,c,p,8c7,p,8c7,p,8c7"
      - delay: 10s
      - lambda: |-
          auto call = id(ring_light).turn_on();
          call.set_effect(id(last_clock_effect));
          call.perform();
  on_stopwatch_minute:
    then:
      - rtttl.play: "chime:d=16,o=6,b=120:c"
  on_timer_started:
    then:
      - rtttl.play: "timer_start:d=16,o=6,b=120:c,e,g"
  on_timer_stopped:
    then:
      - rtttl.play: "timer_stop:d=16,o=6,b=120:g,e,c"
  on_stopwatch_started:
    then:
      - rtttl.play: "sw_start:d=16,o=6,b=120:c7"
  on_stopwatch_paused:
    then:
      - rtttl.play: "sw_pause:d=16,o=6,b=120:c7,p,c7"
  on_stopwatch_reset:
    then:
      - rtttl.play: "sw_reset:d=16,o=6,b=120:c,d,e,f,g"

light:
  # Main LED Rings Configuration (WS2812)
  - id: ring_light
    name: "Ring Light"
    platform: esp32_rmt_led_strip
    rgb_order: GRB
    chipset: ws2812
    pin: GPIO10
    num_leds: 108
    gamma_correct: 2.2
    # WARNING: High brightness draws significant current.
    # Increasing these values above 75% will exceed the devices electrical current limits and may cause overheating and physical damage
    color_correct: [75%, 75%, 75%]
    web_server:
      sorting_group_id: sorting_clock
    on_state:
      - lambda: |-
          if (id(ring_light).remote_values.is_on()) {
            std::string effect = id(ring_light).get_effect_name();
            // Store the active "Clock" effect for reboot restoration
            // Ignore temporary effects like Timer or Stopwatch
            if (effect == "Clock" || effect == "Clock (Fade)" || effect == "Clock (Rainbow)" || effect == "Clock (RGB)" || effect == "Clock (Mono)") {
              id(last_clock_effect) = effect;
            }
          }
    effects:
      # Standard Steps
      - addressable_lambda:
          name: Clock
          update_interval: 50ms
          lambda: |-
            id(RingClock)->set_state(ring_clock::state::time);
            id(RingClock)->addressable_lights_lambdacall(it);
      # RGB Theme (Custom hand overrides in YAML/C++ logic)
      - addressable_lambda:
          name: "Clock (RGB)"
          update_interval: 50ms
          lambda: |-
            id(RingClock)->set_state(ring_clock::state::time);
            id(RingClock)->addressable_lights_lambdacall(it);
      # Monochromatic Theme
      - addressable_lambda:
          name: "Clock (Mono)"
          update_interval: 50ms
          lambda: |-
            id(RingClock)->set_state(ring_clock::state::time);
            id(RingClock)->addressable_lights_lambdacall(it);
      # Smooth Fading Steps
      - addressable_lambda:
          name: "Clock (Fade)"
          update_interval: 33ms
          lambda: |-
            id(RingClock)->set_state(ring_clock::state::time_fade);
            id(RingClock)->addressable_lights_lambdacall(it);
      # Rainbow Color steps
      - addressable_lambda:
          name: "Clock (Rainbow)"
          update_interval: 33ms
          lambda: |-
            id(RingClock)->set_state(ring_clock::state::time_rainbow);
            id(RingClock)->addressable_lights_lambdacall(it);
      # Timer Visuals
      - addressable_lambda:
          name: "Timer"
          update_interval: 100ms
          lambda: |-
            id(RingClock)->set_state(ring_clock::state::timer);
            id(RingClock)->addressable_lights_lambdacall(it);
      # Stopwatch Visuals
      - addressable_lambda:
          name: "Stopwatch"
          update_interval: 100ms
          lambda: |-
            id(RingClock)->set_state(ring_clock::state::stopwatch);
            id(RingClock)->addressable_lights_lambdacall(it);
            
  # Customisation Keys: Hands
  # These are dummy lights that allow the user to pick colors in the UI
  - platform: rgb
    id: hour_hand_color
    name: "Hour Hand"
    restore_mode: RESTORE_DEFAULT_OFF
    default_transition_length: 0s
    red: output_hour_red
    green: output_hour_green
    blue: output_hour_blue
    web_server:
      sorting_group_id: sorting_clock_led
      
  - platform: rgb
    id: minute_hand_color
    name: "Minute Hand"
    restore_mode: RESTORE_DEFAULT_OFF
    default_transition_length: 0s
    red: output_minute_red
    green: output_minute_green
    blue: output_minute_blue
    web_server:
      sorting_group_id: sorting_clock_led
      
  - platform: rgb
    id: second_hand_color
    name: "Second Hand"
    restore_mode: RESTORE_DEFAULT_OFF
    default_transition_length: 0s
    red: output_second_red
    green: output_second_green
    blue: output_second_blue
    web_server:
      sorting_group_id: sorting_clock_led
      
  # Customisation Keys: Markers
  - platform: rgb
    id: marker_color
    name: "Markers"
    restore_mode: RESTORE_DEFAULT_OFF
    default_transition_length: 1s
    red: output_marker_red
    green: output_marker_green
    blue: output_marker_blue
    web_server:
      sorting_group_id: sorting_clock_led
    effects:
      - random:
      
  # Customisation Keys: Notification/Background
  - platform: rgb
    id: notification_color
    name: "Notification"
    restore_mode: RESTORE_DEFAULT_OFF
    default_transition_length: 1s
    red: output_notification_red
    green: output_notification_green
    blue: output_notification_blue
    web_server:
      sorting_group_id: sorting_clock_led
    effects:
      - random:
      - pulse:
          name: "Fast Pulse"
          transition_length: 0.5s
          update_interval: 0.5s
          min_brightness: 50%
          max_brightness: 100%
      - pulse:
          name: "Slow Pulse"
          transition_length: 500ms
          update_interval: 2s
      # Custom animations triggered by sensors
      - automation:
          name: "Sensors: Dual Bars"
          sequence: []
      - automation:
          name: "Sensors: Temperature Bar"
          sequence: []
      - automation:
          name: "Sensors: Humidity Bar"
          sequence: []
      - automation:
          name: "Sensors: Dual Ticks"
          sequence: []
      - automation:
          name: "Sensors: Temperature Tick"
          sequence: []
      - automation:
          name: "Sensors: Humidity Tick"
          sequence: []
      - automation:
          name: "Sensors: Dual Glow"
          sequence: []
      - automation:
          name: "Sensors: Temperature Glow"
          sequence: []
      - automation:
          name: "Sensors: Humidity Glow"
          sequence: []

output:
  # "Dummy" outputs needed to bind the RGB lights above
  # They don't control hardware directly
  - platform: template
    id: output_hour_red
    type: float
    write_action: {}
  - platform: template
    id: output_hour_green
    type: float
    write_action: {}
  - platform: template
    id: output_hour_blue
    type: float
    write_action: {}
  - platform: template
    id: output_minute_red
    type: float
    write_action: {}
  - platform: template
    id: output_minute_green
    type: float
    write_action: {}
  - platform: template
    id: output_minute_blue
    type: float
    write_action: {}
  - platform: template
    id: output_second_red
    type: float
    write_action: {}
  - platform: template
    id: output_second_green
    type: float
    write_action: {}
  - platform: template
    id: output_second_blue
    type: float
    write_action: {}
  - platform: template
    id: output_marker_red
    type: float
    write_action: {}
  - platform: template
    id: output_marker_green
    type: float
    write_action: {}
  - platform: template
    id: output_marker_blue
    type: float
    write_action: {}
  - platform: template
    id: output_notification_red
    type: float
    write_action: {}
  - platform: template
    id: output_notification_green
    type: float
    write_action: {}
  - platform: template
    id: output_notification_blue
    type: float
    write_action: {}
