uart:
  id: uart_bus
  baud_rate: 256000
  tx_pin: GPIO21
  rx_pin: GPIO20
  parity: NONE
  stop_bits: 1

ld2410:

binary_sensor:
  - platform: ld2410
    has_target:
      name: Occupancy
      on_press:
        then:
          - light.turn_on:
              id: ring_light
              brightness: 50%
      on_release:
        then:
          - light.turn_on:
              id: ring_light
              brightness: 25%
    has_moving_target:
      name: Moving Target
    has_still_target:
      name: Still Target
