ld2410:

sensor:
  - platform: aht10
    variant: AHT20
    address: 0x38
    temperature:
      id: temp_sensor
      name: "Temperature"
      icon: mdi:thermometer
      web_server:
        sorting_group_id: sorting_sensors
    humidity:
      id: humidity_sensor
      name: "Humidity"
      icon: mdi:water-percent
      web_server:
        sorting_group_id: sorting_sensors
  - platform: adc
    pin: GPIO4
    name: "Brightness"
    id: brightness_sensor
    icon: mdi:brightness-6
    accuracy_decimals: 0
    web_server:
      sorting_group_id: sorting_sensors
    attenuation: 12db
    update_interval: 5s
    unit_of_measurement: "%"
    filters:
      - calibrate_linear:
          - 0.0 -> 0.0
          - 3.0 -> 100.0
      - lambda: |-
          float interference = id(RingClock)->get_interference_factor();
          
          // Multiplicative adjustment (as a divisor/factor)
          // Using a softer weight of 1.8 to reflect the "slightly less" request
          float factor = 1.0f / (1.0f + (interference * 1.8f));
          
          float adjusted_value = x * factor;
          
          return adjusted_value < 0 ? 0 : (adjusted_value > 100 ? 100 : adjusted_value);
      - sliding_window_moving_average:
          window_size: 5
          send_every: 1

binary_sensor:
  - platform: ld2410
    has_target:
      name: Occupancy
      web_server:
        sorting_group_id: sorting_sensors
      on_press:
        - if:
            condition:
              - switch.is_on: presense_detection
            then:
              - light.turn_on:
                  id: ring_light
                  brightness:  !lambda 'return id(standard_percentage)->state/100;'
                  transition_length: 1s
      on_release:
        - if:
            condition:
              - switch.is_on: presense_detection
            then:
              - light.turn_on:
                  id: ring_light
                  brightness:  !lambda 'return id(low_percentage)->state/100;'
                  transition_length: 1s
    has_moving_target:
      name: Moving Target
      web_server:
        sorting_group_id: sorting_sensors
    has_still_target:
      name: Still Target
      web_server:
        sorting_group_id: sorting_sensors
  - platform: gpio
    pin: GPIO3
    name: "Presence"
    web_server:
      sorting_group_id: sorting_sensors
    device_class: presence

switch:
  - platform: template
    name: "Presense Detection Dimming"
    id: presense_detection
    optimistic: True
    restore_mode: RESTORE_DEFAULT_OFF
    web_server:
      sorting_group_id: sorting_clock
