substitutions:
  # Default offsets to compensate for internal heat
  # These can be adjusted via the web UI or Home Assistant
  temp_offset_default: "-4.0"
  humidity_offset_default: "0.0"

# I2C Bus Config (Used by RTC and Environmental Sensor)
i2c:
  scl: GPIO5
  sda: GPIO6
  scan: true
  
# UART used for Radar Sensor (LD2410) communication
uart:
  id: uart_bus
  baud_rate: 256000
  tx_pin: GPIO0
  rx_pin: GPIO1
  parity: NONE
  stop_bits: 1

ld2410:
  id: radar

sensor:
  # AHT20 Temperature & Humidity Sensor
  - platform: aht10
    id: aht_sensor
    variant: AHT20
    address: 0x38
    update_interval: 15s
    temperature:
      id: temp_sensor
      name: "Temperature"
      icon: mdi:thermometer
      accuracy_decimals: 1
      filters:
        - lambda: return x + id(temp_offset).state;
      web_server:
        sorting_group_id: sorting_sensors
        sorting_weight: 1
    humidity:
      id: humidity_sensor
      name: "Humidity"
      icon: mdi:water-percent
      accuracy_decimals: 0
      filters:
        - lambda: |-
            // Get ambient (corrected) and raw (internal) temperature
            float t_amb = id(temp_sensor).state;
            float t_raw = t_amb - id(temp_offset).state;
            
            if (std::isnan(t_amb) || std::isnan(x)) return x;
            
            // Saturation Vapor Pressure formula (Magnus-Tetens)
            auto esat = [](float t) {
              return 6.112f * expf((17.67f * t) / (t + 243.5f));
            };
            
            // Correct RH based on the ratio of saturation vapor pressures
            // RH_amb = RH_raw * (e_sat(T_raw) / e_sat(T_amb))
            float rh_corr = x * (esat(t_raw) / esat(t_amb));
            
            // Apply the manual trim offset on top of the physics-based correction
            return rh_corr + id(humidity_offset).state;
      web_server:
        sorting_group_id: sorting_sensors
        sorting_weight: 2
        
  # Light Sensor (ADC)
  - platform: adc
    pin: GPIO4
    name: "Brightness"
    id: brightness_sensor
    icon: mdi:brightness-6
    accuracy_decimals: 0
    web_server:
      sorting_group_id: sorting_sensors
      sorting_weight: 7
    attenuation: 12db
    update_interval: never # Manually triggered by time routine below
    unit_of_measurement: "%"
    filters:
      # Map raw voltage (0-3V) into a percentage
      - calibrate_linear:
          - 0.0 -> 0.0
          - 3.0 -> 100.0

binary_sensor:
  # MMwave Radar Presence Detection (LD2410)
  - platform: ld2410
    has_target:
      id: radar_occupancy
      name: Occupancy
      web_server:
        sorting_group_id: sorting_sensors
        sorting_weight: 5
    has_moving_target:
      id: radar_moving
      name: Moving Target
      web_server:
        sorting_group_id: sorting_sensors
        sorting_weight: 3
    has_still_target:
      id: radar_still
      name: Still Target
      web_server:
        sorting_group_id: sorting_sensors
        sorting_weight: 4
        
  # LD2410 Presence input
  - platform: gpio
    id: radar_presence
    pin: GPIO3
    name: "Presence"
    web_server:
      sorting_group_id: sorting_sensors
      sorting_weight: 6
    device_class: presence
    icon: mdi:target-account
    filters:
      - delayed_off: 60s
    on_press:
      - if:
          condition:
            - switch.is_on: presense_detection
          then:
            - light.turn_on:
                id: ring_light
                brightness:  !lambda 'return id(standard_percentage)->state/100;'
                transition_length: 1s
    on_release:
      - if:
          condition:
            - switch.is_on: presense_detection
          then:
            - light.turn_on:
                id: ring_light
                brightness:  !lambda 'return id(low_percentage)->state/100;'
                transition_length: 1s

# System Output Hardware
output:
  # Buzzer connected to GPIO7
  - platform: ledc
    pin: GPIO7
    id: buzzer

# RTTTL (Ring Tone Text Transfer Language)
# Used for playing melodies (alarms, notifications)
rtttl:
  output: buzzer
  id: buzzer_rtttl
  gain: 90%

