esphome:
  project:
    name: "NIXlabs.AL60"
    version: "${version}"
  # These reference the substitutions defined in the main yaml file
  name: "${name}"
  friendly_name: "${friendly_name}"
  name_add_mac_suffix: true
  platformio_options:
    board_build.flash_mode: dio
    
esp32:
  board: esp32-c3-devkitm-1
  variant: ESP32C3
  framework:
    type: esp-idf

# Logging Configuration
logger:
  level: DEBUG
  logs:
    # Reduce noise from sensors and date components
    sensor: INFO
    datetime.datetime_entity: INFO

# Native API for Home Assistant
api:
  # No encryption key by default to make local access easier
  # Can be added in local overrides if desired
  reboot_timeout: 0s

# Over-The-Air Updates
ota:
  - platform: http_request # Allow pulling updates from the network
  - platform: web_server   # Allow uploading .bin via web UI
  - platform: esphome      # Allow updating via ESPHome dashboard

# Required for http_request OTA platform and timezone discovery
http_request:
json:

# Update Check
# Compares current version against the manifest to notify of updates
update:
  - platform: http_request
    id: firmware_update
    name: Firmware Update
    source: https://n33174.github.io/nixr_dev/firmware/manifest.json
    web_server:
      sorting_group_id: sorting_system

# Captive Portal for fallback wifi configuration
captive_portal:

# Bluetooth LE Provisioning (Improv)
# Allows setting up WiFi from a phone app locally
esp32_improv:
  authorizer: none

# Serial Provisioning
# Allows setting up WiFi via USB cable
improv_serial:

# Web Interface Configuration
web_server:
  port: 80
  version: 3
  # Custom styling to match NIX labs branding
  css_url: https://n33174.github.io/nixr_dev/static/www.css
  
  # Organize the web entities into logical groups
  sorting_groups:
    - id: sorting_time
      name: "Time Settings"
      sorting_weight: 10
    - id: sorting_clock
      name: "Clock Settings"
      sorting_weight: 20
    - id: sorting_clock_led
      name: "Clock LED Customisation"
      sorting_weight: 25
    - id: sorting_sensors
      name: "Sensors"
      sorting_weight: 30
    - id: sorting_timer
      name: "Timer & Stopwatch"
      sorting_weight: 40
    - id: sorting_alarm
      name: "Alarm"
      sorting_weight: 45
    - id: sorting_other
      name: "Other"
      sorting_weight: 50
    - id: sorting_system
      name: "System"
      sorting_weight: 60